### ISSUE TITLE
ReSet buttom error

### ISSUE THREAD

**Issue by stinglin1130** [schale-tos/TOSAddon#27]
こんにちは、最後のバージョンにアップデートした後、リセット ボタンの位置が消えてしまいました。この問題を修正していただけますか? ありがとうございます。

![未命名](https://github.com/schale-tos/TOSAddon/assets/71560555/eee6f9dd-bef4-4148-aaec-d1e7c4fae224)

**Comment by schale-tos** [comment]
@stinglin1130 クイックスロットのリフレッシュボタンの位置を修正した v1.0.8 をリリースしました。
アドオンマネージャーから更新してご利用ください。

**Comment by stinglin1130** [comment]
分かりました、ありがとう。
Got it, Thank you.
